### ISSUE TITLE
xDiskAccessPath - Cannot re-create Access Path mapping

### ISSUE THREAD

**Issue by Zuldan** [PowerShell/xStorage#66] opened 2016-11-11 01:51 UTC
@PlagueHO thank you for a fantastic resource. I've been using it in production and it's been working a treat. I have come across a small issue where the resource is not keeping the desired state in certain situations.

Say I have 3x disks mounted to 3x directories

C:\MountPoint\SQLDATA01 (maps to disk 2)
C:\MountPoint\SQLDATA02 (maps to disk 3)
C:\MountPoint\SQLDATA03 (maps to disk 4)

**Situation 1:**

I delete C:\MountPoint\SQLDATA03 then run another consistency check. The resource doesn't re-attach the disk back to C:\MountPoint\SQLDATA03. Instead the following message appears "Not enough available capacity".

```
VERBOSE: [S12AUMDC01TST83]: LCM:  [ Start  Resource ]  [[xDiskAccessPath]DiskAccessPathSQLDATA03]
VERBOSE: [S12AUMDC01TST83]: LCM:  [ Start  Test     ]  [[xDiskAccessPath]DiskAccessPathSQLDATA03]
VERBOSE: [S12AUMDC01TST83]:                            [[xDiskAccessPath]DiskAccessPathSQLDATA03] Test-TargetResource: Testing Disk '4' status for access path 'C:\MountPoint\SQLDATA03'.
VERBOSE: [S12AUMDC01TST83]:                            [[xDiskAccessPath]DiskAccessPathSQLDATA03] Test-TargetResource: Checking if disk number '4' is initialized.
VERBOSE: [S12AUMDC01TST83]:                            [[xDiskAccessPath]DiskAccessPathSQLDATA03] Test-TargetResource: A volume assigned to access path 'C:\MountPoint\SQLDATA03\' was not found.
VERBOSE: [S12AUMDC01TST83]: LCM:  [ End    Test     ]  [[xDiskAccessPath]DiskAccessPathSQLDATA03]  in 0.0320 seconds.
VERBOSE: [S12AUMDC01TST83]: LCM:  [ Start  Set      ]  [[xDiskAccessPath]DiskAccessPathSQLDATA03]
VERBOSE: [S12AUMDC01TST83]:                            [[xDiskAccessPath]DiskAccessPathSQLDATA03] Set-TargetResource: Setting Disk '4' status for access path 'C:\MountPoint\SQLDATA03'.
VERBOSE: [S12AUMDC01TST83]:                            [[xDiskAccessPath]DiskAccessPathSQLDATA03] Set-TargetResource: Checking disk number '4' partition style.
VERBOSE: [S12AUMDC01TST83]:                            [[xDiskAccessPath]DiskAccessPathSQLDATA03] Set-TargetResource: Disk number '4' is already initialized with GPT.
VERBOSE: [S12AUMDC01TST83]:                            [[xDiskAccessPath]DiskAccessPathSQLDATA03] Set-TargetResource: Creating partition on disk number '4' using all free space.
Invoke-CimMethod : Not enough available capacity
```
**Situation 2:**

If I change the resource config to say instead of disk 4 mapping to C:\MountPoint\SQLDATA03, it should map to C:\SQLDATA03, the same message appears, "Not enough available capacity".

**Comment by PlagueHO** [comment] 2016-11-11 06:38
Hi @Zuldan, awesome it is working OK (except for these glitches). I think I know what might be causing the problem - the resource is not correctly detecting that the partition has already been created, so is trying to create a new one (which reports that there is no capacity to add a new partition).

I'll put some work into writing some tests to confirm this this weekend and then create a fix (good old TDD methodology). :grin:

**Comment by Zuldan** [comment] 2016-11-11 09:22
Thank you very much @PlagueHO

**Comment by PlagueHO** [comment] 2016-11-14 07:09
@Zuldan - anytime sir! I ran out of time this weekend and tonight, but I'll get onto this tomorrow night. Hope that is OK?

**Comment by Zuldan** [comment] 2016-11-14 07:55
No problem at all ;-)

**Comment by PlagueHO** [comment] 2016-11-15 07:33
Hi @Zuldan, I'm just working on adding tests for this scenario (so I can then write the fix) and have a question: when you say you delete the mount point: are you deleting the folder that the mount point was mounted to or are you unmounting the access path using a cmdlet or GUI? I'm just trying to write tests that replicate this behavior.

**Comment by Zuldan** [comment] 2016-11-15 07:37
@PlagueHO I'm deleting the folder.

**Comment by PlagueHO** [comment] 2016-11-15 07:42
@Zuldan - Ok cool! I've managed to replicate it by using ```Remove-PartitionAccessPath``` to remove the mount. So, I've not got failing tests.

**Comment by PlagueHO** [comment] 2016-11-15 09:02
@Zuldan - making good progress on this. I have found the bug and just reworking the code to better support this use case. I'll try and get this PR through tomorrow night.

**Comment by Zuldan** [comment] 2016-11-15 09:31
Cool! thanks for the update.

**Comment by PlagueHO** [comment] 2016-11-16 08:16
Hi @Zuldan - The code change is finished including integration/regression tests to cover this scenario. I've still got to complete the unit tests though - which I aim to complete tomorrow night.

If you're feeling enthusiastic you can try out the new version [here in my fork](https://github.com/PlagueHO/xStorage/tree/Fix-66/xDiskAccessPath-Fail-Remap).

**Comment by Zuldan** [comment] 2016-11-17 06:41
@PlagueHO I can confirm it's now working as expected.

**Comment by PlagueHO** [comment] 2016-11-17 07:21
Awesome! Thanks @Zuldan. I was going to try and get the unit tests done tonight but I'm knackered and will just end up doing something dumb. So I'll get them done tomorrow night :grin:

**Comment by PlagueHO** [comment] 2016-11-18 22:40
@kwirkykat  - I'll include the conversion of the integration tests workspace folder over to $TestDrive in the PR for this issue. I need to include this because all my tests broke :grin:

**Comment by PlagueHO** [comment] 2016-11-19 21:27
@kwirkykat - another question: Since the recent changes to PSSA checking (I'm not sure if it was a change to DSCResource.Tests or PSSA), but the WMI cmdlets that xDisk uses are being flagged as PSSA violations. So I can't submit the PR for this the xDiskAccessPath fix without resolving this.

xDisk uses CIM by default but falls back to WMI if that fails. I'm fairly sure we can remove the WMI calls safely, but someone must have added the fall back to WMI for a reason (unfortunately the comments don't say why this was done). So removing them may cause failures in earlier OS's.

So:
Option 1 - remove the WMI calls
Option 2 - suppress the WMI PSSA violations

What are your thoughts?

**Comment by PlagueHO** [comment] 2016-11-20 04:23
@Zuldan - I've completed the PR now and it just needs to go through the review process.

**Comment by Zuldan** [comment] 2016-11-20 05:12
Thanks so much @PlagueHO. Apologies for the additional work this has created. The contribution of your personal time to the community is invaluable.

**Comment by PlagueHO** [comment] 2016-11-20 19:16
@Zuldan - always a pleasure! And this needed to be done. I'm actually much happier with the design pattern now as it handles many other scenarios. I'll be copying this design over to xDisk when I have the time because xDisk will suffer from the similar problems.

This new design will also better support the future "Destructive" flag to allow rewriting the partition table.

**Closed** 2016-12-02 22:17 UTC
Labels: bug, in progress
