### ISSUE TITLE
Duplicate Identical Module Versions Break Import-DSCResource and Publish-AzureVMDscConfiguration

### ISSUE THREAD

**Issue by timomta** [PowerShell/xStorage#34] opened 2016-04-22 20:30 UTC
When I install the module, I get duplicate entries. This causes Publish-AzureVMDSCConfiguration to fail when attempting to resolve the module.

Below is the output of the installation showing the dup. xStorage was not previously installed on this machine, so it was not preexisting.

PS C:\Program Files\WindowsPowerShell\Modules> Install-Module xStorage

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): y
PS C:\Program Files\WindowsPowerShell\Modules> get-module -ListAvailable -FullyQualifiedName xStorage | fl

Name              : xStorage
Path              : C:\Program Files\WindowsPowerShell\Modules\xStorage\2.5.0.0\xStorage.psd1
Description       : This module contains all resources related to the PowerShell Storage module, or pertaining to disk
                    management.
ModuleType        : Manifest
Version           : 2.5.0.0
NestedModules     : {}
ExportedFunctions :
ExportedCmdlets   :
ExportedVariables :
ExportedAliases   :

Name              : xStorage
Path              : C:\Program Files\WindowsPowerShell\Modules\xStorage\2.5.0.0\xStorage.psd1
Description       : This module contains all resources related to the PowerShell Storage module, or pertaining to disk
                    management.
ModuleType        : Manifest
Version           : 2.5.0.0
NestedModules     : {}
ExportedFunctions :
ExportedCmdlets   :
ExportedVariables :
ExportedAliases   :

**Comment by TravisEz13** [comment] 2016-04-22 20:59
What is $env:psmodulepath  Do you have a path listed twice?

**Comment by timomta** [comment] 2016-04-22 21:21
Hi Travis, no C:\Program Files\WindowsPowerShell\Modules shows a single directory for xStorage and a single 2.5.0.0 within that directory:

**Comment by TravisEz13** [comment] 2016-04-22 21:25
What is your `$env:psmodulepath` when running in Powershell?
Can you run "$env:psmodulePath" and send the output?

**Comment by timomta** [comment] 2016-04-22 21:31
Hi Travis,

 

Here is my path:

C:\Users\tomta\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Window

sPowerShell\v1.0\Modules\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules\;C:\Program Files\Mic

rosoft Message Analyzer\PowerShell\;C:\Program Files\WindowsPowerShell\Modules\;C:\Program Files (x86)\Microsoft SDKs\Az

ure\PowerShell\ResourceManager\AzureResourceManager\;C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManag

ement\;C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\Storage\

 

I checked all the directories listed in it and only C:\Users\tomta\Documents\WindowsPowerShell\Modules contains xStorage. Note that for some reason C:\Users\tomta\Documents\WindowsPowerShell\Modules is listed twice though. I’ll fix that and see if that is the problem…

**Comment by timomta** [comment] 2016-04-22 21:43
Travis, that duplicate entry in my module path was the problem. Some extraordinarily helpful installer must have added it sometime in the past and I didn’t see it.

 

Thanks for prompting me to review that path.

**Comment by TravisEz13** [comment] 2016-04-22 21:44
Here is your path reformated to one path per line and sorted, the problem is in bold.  

* C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\;
* C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement\;
* C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\Storage\
* C:\Program Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules\;
* C:\Program Files\Microsoft Message Analyzer\PowerShell\;
* **C:\Program Files\WindowsPowerShell\Modules;**
* **C:\Program Files\WindowsPowerShell\Modules\;**
* C:\Users\tomta\Documents\WindowsPowerShell\Modules;
* C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\;

Please file an issue for this on [https://windowsserver.uservoice.com/forums/301869-powershell](PowerShell User Voice)

I suspect when you installed the azure SDK it duplicated the path.

To fix this open (this is windows 10 the names may vary slightly on other Oss)

1. Open Control panel 
2. Open System and Security 
3. Open System 
4. Open Advanced System Setting 
5. Open Environment variables
6. In system varibales find PSModule Path, click it 
7. click edit 
8. Remove any reference to `C:\Program Files\WindowsPowerShell\Modules`
9. click ok
10. close any powershell windows
11. if you are using any application other than windows explore to launch powershell, close those as well.

It should now be fixed

**Comment by TravisEz13** [comment] 2016-04-22 21:45
Forgot to add, please confirm this resolves the issue so I can close this question.

**Comment by timomta** [comment] 2016-04-22 21:51
Confirmed: something added that path to my system environment PSModulePath. I remove it via Control Panel and everything is working as expected.

**Comment by TravisEz13** [comment] 2016-04-22 22:06
Thanks for confirming, If you please the powershell behavior here is incorrect, please file an issue  on [PowerShell UserVoice](https://windowsserver.uservoice.com/forums/301869-powershell)

**Closed by TravisEz13** 2016-04-22 22:06 UTC
Labels: question

**Comment by timomta** [comment] 2016-04-22 22:26
Here you go Travis, please vote it up: https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/13545987-duplicate-psmodulepath-entries-cause-module-resolu

**Comment by timomta** [comment] 2016-04-22 23:14
Issue logged here on PS UserVoice, please vote it up if you have this issue: https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/13545987-duplicate-psmodulepath-entries-cause-module-resolu
